name: Go CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install reporting tools
        run: |
          go install gotest.tools/gotestsum@latest
          go install github.com/vakenbolt/go-test-report@latest
          
      - name: Run All Tests & Generate Report
        run: |
          # 1. Bật server ở chế độ background
          go run main.go &
          
          # 2. Đợi cho đến khi server sẵn sàng (ping thành công)
          timeout 30s sh -c 'until curl -s http://127.0.0.1:8080/ping; do sleep 1; done'
          
          # 3. Chạy TẤT CẢ các test (Unit + Automation) trong 1 lần duy nhất
          # Lệnh này sẽ tạo ra 1 file JSON hoàn hảo cho go-test-report
          go test -json -v -tags automation ./... > report.json || true
          
          # 4. Hiển thị lỗi lên Annotations của GitHub
          cat report.json | gotestsum --format github-actions
          
          # 5. Tạo báo cáo HTML từ file JSON duy nhất này (Dùng ống dẫn | )
          cat report.json | go-test-report -o report.html

      - name: Upload Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Report-HTML
          path: report.html
